# FloxAI Minimal - Just AI Chat Capabilities
# Example composition using base + LLM components only

version = 1

[vars]
FLOXAI_MODE = "minimal"
FLOXAI_COMPONENTS = "base,llm"

[include]
environments = [
    { remote = "8bittacosupreme/floxai-base" },
    { remote = "8bittacosupreme/floxai-llm" }
]

[profile]
common = '''
echo "FloxAI Minimal Environment Ready"
echo "Components: Base Runtime + LLM"
echo "Missing: RAG/Knowledge Base (layer floxai-rag if needed)"
'''